version: 2

project_name: foostash

before:
  hooks:
    - go mod tidy

builds:
  - id: foostash
    main: ./cmd/cli
    binary: foostash
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/Omotolani98/foostash/cli.Version={{.Version}}
      - -X github.com/Omotolani98/foostash/cli.Commit={{.ShortCommit}}
      - -X github.com/Omotolani98/foostash/cli.Date={{.Date}}

archives:
  - id: foostash
    builds:
      - foostash
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"

brews:
  - repository:
      owner: Omotolani98
      name: homebrew-tap
    name: foostash
    homepage: https://github.com/Omotolani98/foostash
    description: Open-source secrets and environment variable manager
    license: MIT
    install: |
      bin.install "foostash"

release:
  github:
    owner: Omotolani98
    name: foostash
  draft: false
  prerelease: auto
